#!/bin/bash

test_run_stop()
{
    TASK_ID=$(dist/tasks run python3 -m http.server)
    sleep 0.1
    curl -f localhost:8000 &> /dev/null
    value=$?
    if [ $? -ne 0 ]; then
        echo "failed"
        return 1
    fi
    dist/tasks stop $TASK_ID
    sleep 0.1
    curl -f localhost:8000 &> /dev/null
    if [ $? -eq 0 ]; then
        echo "failed"
        return 1
    fi
    echo "passed"
    return 0
}

build/build

test_run_stop