#!/bin/bash

test_run_stop()
{
    TASK_ID=$(dist/tasks run python3 -m http.server)
    sleep 0.1
    curl -f localhost:8000 &> /dev/null
    value=$?
    if [ $? -ne 0 ]; then
        echo "failed (not running)"
        return 1
    fi
    dist/tasks stop $TASK_ID
    sleep 0.1
    curl -f localhost:8000 &> /dev/null
    if [ $? -eq 0 ]; then
        echo "failed (not stopped)"
        return 1
    fi
    echo "passed"
    return 0
}

test_status()
{
    TASK_ID=$(dist/tasks run yes)
    sleep 0.1
    result=$(dist/tasks status $TASK_ID)
    if [ $result != "running" ]; then
        echo "failed ('$result' when running)"
        return 1
    fi
    dist/tasks stop $TASK_ID
    result=$(dist/tasks status $TASK_ID)
    if [ $result != "stopped" ]; then
        echo "failed ('$result' when stopped)"
        return 1
    fi
    echo "passed"
    return 0
}

mkdir -p dist/taskshome/tasks

build/build

printf "Test run/stop: "
test_run_stop

printf "Test status: "
test_status